[package]
name = "codegen-cfg"
version = "0.1.1"
edition = "2021"
description = "A codegen tool for Rust `cfg` expressions"
license.workspace = true
repository.workspace = true

[dependencies]
itertools = "0.10.5"
nugine-rust-utils = { version = "0.1.1", features = ["std"] }
