[package]
name = "bool-logic"
version = "0.1.4-dev"
edition = "2021"
description = "A library for manipulating and evaluating boolean expressions"
license.workspace = true
repository.workspace = true

[dependencies]
nugine-rust-utils = "0.2.1"
replace_with = "0.1.7"
